version: 2
jobs:
  build:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: yarn install --silent
      - run: 
          name: Audit dependencies
          command: yarn audit
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
  test:
    docker:
      - image: node:11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          name: Run linter
          command: yarn lint
  deploy:
    docker:
      - image: node:11
    steps:
      - setup_remote_docker
      - run: |
          TAG=$(git describe --tags)
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t thomasgosse/selection:$TAG .
          docker push thomasgosse/selection:$TAG
      
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master