version: 2
jobs:
  build:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: yarn install --silent
      - run: 
          name: Audit dependencies
          command: yarn audit
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
      - persist_to_workspace:
          root: ./
          paths: [dist]
  test:
    docker:
      - image: node:11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          name: Run linter
          command: yarn lint
  deploy:
    docker:
      - image: node:11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install Firebase
          command: npm install -g firebase-tools
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN
      
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master